### ISSUE TITLE
Deprovisioning is not removing S3 instance from AWS

### ISSUE THREAD

**Issue by VeerMuchandi** [awslabs/aws-servicebroker-s3#2] opened 2018-01-22 22:14 UTC
Provisioning works ok.
When you deprovision, the job completes. But the S3 bucket is not being removed from AWS.

**Comment by jaymccon** [comment] 2018-01-24 00:32
Hi,

At this point this is the expected behavior, see https://github.com/awslabs/aws-servicebroker-s3/blob/master/roles/provision-s3-apb-openshift/files/S3Bucket.yml#L103

The reasoning behind this is that CloudFormation will not gracefully remove buckets that contain data, it is considered the safest approach to leave the bucket behind in case it contains data (like logs) that are required beyond the life of the container.

In the future we may implement deletion of buckets and their contents for dev plans and only retain the buckets on prod plans (possibly even make it optional).

**Comment by jaymccon** [comment] 2018-05-08 07:00
This has been addressed in the latest build, see https://github.com/awslabs/aws-servicebroker/ for more details

**Closed as completed by jaymccon** 2018-05-08 07:00 UTC
